### ISSUE TITLE
It all seems blank with no errors

### ISSUE THREAD

**Issue by Rajan** [erguotou520/vue-fullstack#20]
Both client and servers are running but the page displays nothing but blank.

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>venomjs</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="renderer" content="webkit">
    <link href="/static/favicon.ico" rel="shortcut icon" type="image/x-icon" />
  </head>
  <body>
    <app></app>
    <!-- built files will be auto injected -->
  <script type="text/javascript" src="/app.js"></script></body>
</html>
```

**Comment by Rajan** [comment]
I found errors in the browser console though.

```
Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_1_vue___default.a.locale is not a function
    at eval (eval at <anonymous> (http://localhost:9001/app.js:2097:1), <anonymous>:37:47)
    at Array.forEach (native)
    at eval (eval at <anonymous> (http://localhost:9001/app.js:2097:1), <anonymous>:36:84)
    at Object.<anonymous> (http://localhost:9001/app.js:2097:1)
    at __webpack_require__ (http://localhost:9001/app.js:691:30)
    at fn (http://localhost:9001/app.js:110:20)
    at eval (eval at <anonymous> (http://localhost:9001/app.js:1856:1), <anonymous>:7:67)
    at Object.<anonymous> (http://localhost:9001/app.js:1856:1)
    at __webpack_require__ (http://localhost:9001/app.js:691:30)
    at fn (http://localhost:9001/app.js:110:20)
```

**Comment by erguotou520** [comment]
What the version of `vue-i18n`?

**Comment by Rajan** [comment]
I installed it without i18n when it prompted. Also, updated vue-i18n to the latest. I even tried to remove it from Header.vue and Login.vue. Just re-installed without i18n and here's what I see in the chrome console.

```
[Vue warn]: Error in data(): "TypeError: this.$t is not a function"

found in

---> <XHeader> at /Users/rajanchandi/WebstormProjects/venomjs/client/src/components/Header.vue
       <Root>
warn @ vue.common.js?e881:436
vue.common.js?e881:525 TypeError: this.$t is not a function
    at VueComponent.data (eval at <anonymous> (app.js:2160), <anonymous>:42:43)
    at getData (eval at <anonymous> (app.js:811), <anonymous>:3070:17)
    at initData (eval at <anonymous> (app.js:811), <anonymous>:3039:7)
    at initState (eval at <anonymous> (app.js:811), <anonymous>:2976:5)
    at VueComponent.Vue._init (eval at <anonymous> (app.js:811), <anonymous>:4000:5)
    at new VueComponent (eval at <anonymous> (app.js:811), <anonymous>:4171:12)
    at createComponentInstanceForVnode (eval at <anonymous> (app.js:811), <anonymous>:3520:10)
    at init (eval at <anonymous> (app.js:811), <anonymous>:3354:45)
    at createComponent (eval at <anonymous> (app.js:811), <anonymous>:4903:9)
    at createElm (eval at <anonymous> (app.js:811), <anonymous>:4846:9)
handleError @ vue.common.js?e881:525
vue.common.js?e881:436 [Vue warn]: Error in created hook: "TypeError: Cannot read property 'form' of undefined"

found in

---> <XHeader> at /Users/rajanchandi/WebstormProjects/venomjs/client/src/components/Header.vue
       <Root>
warn @ vue.common.js?e881:436
vue.common.js?e881:525 TypeError: Cannot read property 'form' of undefined
    at VueComponent.cancelConfig (eval at <anonymous> (app.js:2160), <anonymous>:76:18)
    at VueComponent.boundFn [as cancelConfig] (eval at <anonymous> (app.js:811), <anonymous>:167:12)
    at VueComponent.created (eval at <anonymous> (app.js:2160), <anonymous>:111:10)
    at callHook (eval at <anonymous> (app.js:811), <anonymous>:2558:21)
    at VueComponent.Vue._init (eval at <anonymous> (app.js:811), <anonymous>:4002:5)
    at new VueComponent (eval at <anonymous> (app.js:811), <anonymous>:4171:12)
    at createComponentInstanceForVnode (eval at <anonymous> (app.js:811), <anonymous>:3520:10)
    at init (eval at <anonymous> (app.js:811), <anonymous>:3354:45)
    at createComponent (eval at <anonymous> (app.js:811), <anonymous>:4903:9)
    at createElm (eval at <anonymous> (app.js:811), <anonymous>:4846:9)
handleError @ vue.common.js?e881:525
vue.common.js?e881:7592 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
client.js?7955:160 [HMR] bundle has 1 warnings
client.js?7955:161 ./client/src/stored.js
8:23-44 "export 'STORE_KEY_CONFIG_LANG' was not found in './constants'
vue.common.js?e881:436 [Vue warn]: Error in data(): "TypeError: this.$t is not a function"

found in

---> <Login> at /Users/rajanchandi/WebstormProjects/venomjs/client/src/view/auth/Login.vue
       <Root>
warn @ vue.common.js?e881:436
vue.common.js?e881:525 TypeError: this.$t is not a function
    at VueComponent.data (eval at 451 (1.js:45), <anonymous>:21:41)
    at getData (eval at <anonymous> (app.js:811), <anonymous>:3070:17)
    at initData (eval at <anonymous> (app.js:811), <anonymous>:3039:7)
    at initState (eval at <anonymous> (app.js:811), <anonymous>:2976:5)
    at VueComponent.Vue._init (eval at <anonymous> (app.js:811), <anonymous>:4000:5)
    at new VueComponent (eval at <anonymous> (app.js:811), <anonymous>:4171:12)
    at createComponentInstanceForVnode (eval at <anonymous> (app.js:811), <anonymous>:3520:10)
    at init (eval at <anonymous> (app.js:811), <anonymous>:3354:45)
    at createComponent (eval at <anonymous> (app.js:811), <anonymous>:4903:9)
    at createElm (eval at <anonymous> (app.js:811), <anonymous>:4846:9)
handleError @ vue.common.js?e881:525
vue.common.js?e881:436 [Vue warn]: Property or method "$t" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Login> at /Users/rajanchandi/WebstormProjects/venomjs/client/src/view/auth/Login.vue
       <Root>
warn @ vue.common.js?e881:436
vue.common.js?e881:436 [Vue warn]: Error in render function: "TypeError: _vm.$t is not a function"

found in

---> <Login> at /Users/rajanchandi/WebstormProjects/venomjs/client/src/view/auth/Login.vue
       <Root>
warn @ vue.common.js?e881:436
vue.common.js?e881:525 TypeError: _vm.$t is not a function
    at Proxy.render (eval at 461 (1.js:59), <anonymous>:12:48)
    at VueComponent.Vue._render (eval at <anonymous> (app.js:811), <anonymous>:3905:22)
    at VueComponent.updateComponent (eval at <anonymous> (app.js:811), <anonymous>:2441:21)
    at Watcher.get (eval at <anonymous> (app.js:811), <anonymous>:2780:25)
    at new Watcher (eval at <anonymous> (app.js:811), <anonymous>:2763:12)
    at mountComponent (eval at <anonymous> (app.js:811), <anonymous>:2445:17)
    at VueComponent.Vue$3.$mount (eval at <anonymous> (app.js:811), <anonymous>:7572:10)
    at VueComponent.Vue$3.$mount (eval at <anonymous> (app.js:811), <anonymous>:9671:16)
    at init (eval at <anonymous> (app.js:811), <anonymous>:3360:13)
    at createComponent (eval at <anonymous> (app.js:811), <anonymous>:4903:9)
handleError @ vue.common.js?e881:525
```

**Comment by Rajan** [comment]
One more thing on the client commandline console.

```
 WARNING  Compiled with 1 warnings                                                                                                                 3:49:50 PM

 warning  in ./client/src/stored.js

8:23-44 "export 'STORE_KEY_CONFIG_LANG' was not found in './constants'

[HPM] Upgrading to WebSocket
[HPM] Client disconnected
```

**Comment by erguotou520** [comment]
Do you run `npm run remove:i18n` after prompted?

**Comment by Rajan** [comment]
Yes and here's what it says on the console.

```
$ npm run remove:i18n
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "run" "remove:i18n"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0

npm ERR! missing script: remove:i18n
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rajanchandi/.npm/_logs/2017-05-23T12_48_35_501Z-debug.log
```

**Comment by erguotou520** [comment]
Closed as your project runs ok.
