### ISSUE TITLE
It also fails with i18n and mock server option

### ISSUE THREAD

**Issue by Rajan** [erguotou520/vue-fullstack#21]
```
> node build/dev-server.js

module.js:472
    throw err;
    ^

Error: Cannot find module '/Users/rajanchandi/WebstormProjects/venomjs/build/dev-server.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "run" "client"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! venomjs@0.0.1 client: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the venomjs@0.0.1 client script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the venomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs venomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls venomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rajanchandi/.npm/_logs/2017-05-23T10_28_45_840Z-debug.log
```

**Comment by erguotou520** [comment]
Do you run `npm run remove:mock` after promoted?

**Comment by Rajan** [comment]
Yes. It still says can not get /.
Also, this error in the browser console.

`Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by erguotou520** [comment]
Could you show me your project folder (run `tree`) or git repo?

**Comment by Rajan** [comment]
https://github.com/Rajan/venomjs

**Comment by erguotou520** [comment]
I didn't get any error. You need to run `npm i` firstly, then open two terminal, one runs `npm run mock` and the another runs `npm run client`

**Comment by Rajan** [comment]
It worked for me this time with mock. Although, backend with port 7878 says this.

Cannot GET /

Errors on the browser:

Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/ Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by Rajan** [comment]
Is it possible to avoid mock and i18n? 
They make things a bit confusing for the user of this template.

**Comment by erguotou520** [comment]
Of course you can. I18n is just a front-end module to build international web page and mock server can provide datas before backend server.

**Comment by erguotou520** [comment]
Closed as your project runs ok.
