### ISSUE TITLE
Clean install, npm run dev fails

### ISSUE THREAD

**Issue by D3m1urg0** [erguotou520/vue-fullstack#24]
I just installed the cli
run mongo, then executed npm run dev (or npm run server, it's the same)

the client gives me this:
```
[nodemon] starting `node server/app.js`
(node:14160) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `conn
ect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
Express server listening on 9000, in development mode
events.js:182
      throw er; // Unhandled 'error' event
      ^

TypeError: The "digest" argument is required and must not be undefined
    at pbkdf2 (crypto.js:635:11)
    at Object.exports.pbkdf2Sync (crypto.js:628:10)
    at model.encryptPassword (C:\Users\pietro.caruso\Documents\projects\my-vue-project\server\api\user\user.model.js:139:19)
    at model.<anonymous> (C:\Users\pietro.caruso\Documents\projects\my-vue-project\server\api\user\user.model.js:27:32)
    at VirtualType.applySetters (C:\Users\pietro.caruso\Documents\projects\my-vue-project\node_modules\mongoose\lib\virtualtype.js:94:25)
    at model.Document.set (C:\Users\pietro.caruso\Documents\projects\my-vue-project\node_modules\mongoose\lib\document.js:660:12)
    at model._handleIndex (C:\Users\pietro.caruso\Documents\projects\my-vue-project\node_modules\mongoose\lib\document.js:591:14)
    at model.Document.set (C:\Users\pietro.caruso\Documents\projects\my-vue-project\node_modules\mongoose\lib\document.js:551:24)
    at model.Document (C:\Users\pietro.caruso\Documents\projects\my-vue-project\node_modules\mongoose\lib\document.js:71:12)
    at model.Model (C:\Users\pietro.caruso\Documents\projects\my-vue-project\node_modules\mongoose\lib\model.js:46:12)
    at new model (C:\Users\pietro.caruso\Documents\projects\my-vue-project\node_modules\mongoose\lib\model.js:3666:13)
    at C:\Users\pietro.caruso\Documents\projects\my-vue-project\node_modules\mongoose\lib\model.js:1936:51
    at C:\Users\pietro.caruso\Documents\projects\my-vue-project\node_modules\mongoose\node_modules\async\internal\parallel.js:27:9
    at eachOfArrayLike (C:\Users\pietro.caruso\Documents\projects\my-vue-project\node_modules\mongoose\node_modules\async\eachOf.js:57:9)
    at exports.default (C:\Users\pietro.caruso\Documents\projects\my-vue-project\node_modules\mongoose\node_modules\async\eachOf.js:9:5)
    at _parallel (C:\Users\pietro.caruso\Documents\projects\my-vue-project\node_modules\mongoose\node_modules\async\internal\parallel.js:26:5)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by erguotou520** [comment]
Which version of your nodejs? If getter then `4.x`, please specify a `digest` to the final argument
https://github.com/erguotou520/vue-fullstack/blob/master/template/server/api/user/user.model.js#L139

See:
https://nodejs.org/dist/latest-v4.x/docs/api/crypto.html#crypto_crypto_pbkdf2sync_password_salt_iterations_keylen_digest

https://nodejs.org/api/crypto.html#crypto_crypto_pbkdf2sync_password_salt_iterations_keylen_digest

**Comment by D3m1urg0** [comment]
My node version is 8.1.4

Your solution (adding digests to user.model.js) solved the issue

Thank you

**Comment by erguotou520** [comment]
And I have updated the template
