### ISSUE TITLE
running npm run server fails

### ISSUE THREAD

**Issue by djsheva** [erguotou520/vue-fullstack#27]
```
[dima@zendoPC tmp]$ vue init erguotou520/vue-fullstack testApp

? Project name testapp
? Project description A vue-fullstack project
? Author Dima <d@email.com>
? Use real backend server or mock server Backend
? Port that backend server listen at development environment 9000
? Port that frontend server listen at development environment 9001
? MongoDB uri, '-dev' will be appended in development, default is local uri 
? Need vue-i18n? Yes

   vue-cli · Generated "testApp".

   To get started:
   
     cd testApp
     npm install
     npm run server
     npm run client

[dima@zendoPC tmp]$ cd testApp/
[dima@zendoPC testApp]$ npm i
npm WARN deprecated crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN testapp@0.0.1 No repository field.
npm WARN testapp@0.0.1 scripts['server'] should probably be scripts['start'].
npm WARN testapp@0.0.1 No license field.
npm WARN The package express is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1066 packages in 22.453s
[dima@zendoPC testApp]$ npm run server

> testapp@0.0.1 server /home/dima/tmp/testApp
> nodemon --watch server server/app.js

[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /home/dima/tmp/testApp/server/**/*
[nodemon] starting `node server/app.js`
(node:25247) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
Express server listening on 9000, in development mode
events.js:182
      throw er; // Unhandled 'error' event
      ^

TypeError: The "digest" argument is required and m`ust not be undefined
    at pbkdf2 (crypto.js:635:11)
    at Object.exports.pbkdf2Sync (crypto.js:628:10)
    at model.encryptPassword (/home/dima/tmp/testApp/server/api/user/user.model.js:139:19)
    at model.<anonymous> (/home/dima/tmp/testApp/server/api/user/user.model.js:27:32)
    at VirtualType.applySetters (/home/dima/tmp/testApp/node_modules/mongoose/lib/virtualtype.js:94:25)
    at model.Document.set (/home/dima/tmp/testApp/node_modules/mongoose/lib/document.js:666:12)
    at model._handleIndex (/home/dima/tmp/testApp/node_modules/mongoose/lib/document.js:597:14)
    at model.Document.set (/home/dima/tmp/testApp/node_modules/mongoose/lib/document.js:557:24)
    at model.Document (/home/dima/tmp/testApp/node_modules/mongoose/lib/document.js:76:12)
    at model.Model (/home/dima/tmp/testApp/node_modules/mongoose/lib/model.js:48:12)
    at new model (/home/dima/tmp/testApp/node_modules/mongoose/lib/model.js:3707:13)
    at /home/dima/tmp/testApp/node_modules/mongoose/lib/model.js:1951:51
    at /home/dima/tmp/testApp/node_modules/mongoose/node_modules/async/internal/parallel.js:27:9
    at eachOfArrayLike (/home/dima/tmp/testApp/node_modules/mongoose/node_modules/async/eachOf.js:57:9)
    at exports.default (/home/dima/tmp/testApp/node_modules/mongoose/node_modules/async/eachOf.js:9:5)
    at _parallel (/home/dima/tmp/testApp/node_modules/mongoose/node_modules/async/internal/parallel.js:26:5)
[nodemon] app crashed - waiting for file changes before starting...
^C[dima@zendoPC testApp]$ node -v
v8.2.1
[dima@zendoPC testApp]$ npm -v
5.3.0
```

**Comment by erguotou520** [comment]
https://github.com/erguotou520/vue-fullstack/commit/770cff136f28b534b6ec03f03bd0bc004f4fbeed
Try update the template and re-init.

**Comment by djsheva** [comment]
Yes, thanks, it works now
